export const SETTING_CHANNEL = 'SETTINGS';

export const SETTING_KEYS = {
  SITE_NAME: 'siteName',
  LOGO_URL: 'logoUrl',
  FAVICON: 'favicon',
  LOGIN_PLACEHOLDER_IMAGE: 'loginPlaceholderImage',
  REQUIRE_EMAIL_VERIFICATION: 'requireEmailVerification',
  ADMIN_EMAIL: 'adminEmail',
  SENDER_EMAIL: 'senderEmail',
  META_KEYWORDS: 'metaKeywords',
  META_DESCRIPTION: 'metaDescription',
  HEADER_SCRIPT: 'headerScript',
  AFTER_BODY_SCRIPT: 'afterBodyScript',
  MONTHLY_SUBSCRIPTION_COMMISSION: 'monthlySubscriptionCommission',
  YEARLY_SUBSCRIPTION_COMMISSION: 'yearlySubscriptionCommission',
  VIDEO_SALE_COMMISSION: 'videoSaleCommission',
  GALLERY_SALE_COMMISSION: 'gallerySaleCommission',
  PRODUCT_SALE_COMMISSION: 'productSaleCommission',
  FEED_SALE_COMMISSION: 'feedSaleCommission',
  TIP_COMMISSION: 'tipCommission',
  STREAM_COMMISSION: 'streamCommission',
  MESSAGE_COMMISSION: 'messageCommission',
  CCBILL_CLIENT_ACCOUNT_NUMBER: 'ccbillClientAccountNumber',
  CCBILL_DATALINK_USERNAME: 'ccbillDatalinkUsername',
  CCBILL_DATALINK_PASSWORD: 'ccbillDatalinkPassword',
  CCBILL_SUB_ACCOUNT_NUMBER: 'ccbillSubAccountNumber',
  CCBILL_FLEXFORM_ID: 'ccbillFlexformId',
  CCBILL_SALT: 'ccbillSalt',
  CCBILL_CURRENCY_CODE: 'ccbilCurrencyCode',
  USE_SENDGRID_TRANSPORTER: 'useSengridTransporter',
  SMTP_TRANSPORTER: 'smtpTransporter',
  GOOGLE_ANALYTICS_CODE: 'gaCode',
  MAINTENANCE_MODE: 'maintenanceMode',
  PERFORMER_VERIFY_NUMBER: 'performerVerifyNumber',
  TWITTER_CLIENT_ID: 'twitterClientId',
  TWITTER_CLIENT_SECRET: 'twitterClientSecret',
  GOOGLE_CLIENT_ID: 'googleClientId',
  GOOGLE_CLIENT_SECRET: 'googleClientSecret',
  VIEWER_URL: 'viewerURL',
  PUBLISHER_URL: 'publisherURL',
  SUBSCRIBER_URL: 'subscriberUrl',
  OPTION_FOR_BROADCAST: 'optionForBroadcast',
  OPTION_FOR_PRIVATE: 'optionForPrivate',
  OPTION_FOR_GROUP: 'optionForGroup',
  SECURE_OPTION: 'secureOption',
  ANT_MEDIA_API_ENDPOINT: 'AntMediaApiEndpoint',
  ANT_MEDIA_APPNAME: 'AntMediaAppname',
  ANT_MEDIA_ENTERPRISE: 'AntMediaEnterprise',
  FOOTER_CONTENT: 'footerContent',
  USER_BENEFIT: 'userBenefit',
  ARTIST_BENEFIT: 'artistBenefit',
  GOOGLE_RECAPTCHA_SITE_KEY: 'googleReCaptchaSiteKey',
  GOOGLE_RECAPTCHA_SECRET_KEY: 'googleReCaptchaSecretKey',
  ENABLE_GOOGLE_RECAPTCHA: 'enableGoogleReCaptcha',
  BITPAY_PRODUCTION_MODE: 'bitpayProductionMode',
  BITPAY_API_TOKEN: 'bitpayApiToken',
  TOKEN_CONVERSION_RATE: 'tokenConversionRate',
  STRIPE_PUBLISHABLE_KEY: 'stripePublishableKey',
  STRIPE_SECRET_KEY: 'stripeSecretKey',
  AGORA_APPID: 'agoraAppId',
  AGORA_ENABLE: 'agoraEnable',
  PAYMENT_GATEWAY: 'paymentGateway',
  IDENTITY_ONFIDO_API_TOKEN: 'identityOnfidoApiToken',
  IDENTITY_ONFIDO_SANDBOX: 'identityOnfidoSandbox',
  IDENTITY_ONFIDO_WORKFLOW_ID: 'identityOnfidoWorkflowId',
  IC_NETWORK: 'icNetwork',
  IC_ENABLE_IC_STORAGE: 'icEnableIcStorage',
  IC_HOST: 'icHost',
  IC_HOST_CONTENT_MANAGER: 'icHostContentManager',
  IC_CANISTERS_XRC: 'icXRC',
  IC_CANISTERS_LEDGER: 'icLedger',
  IC_CANISTERS_CKBTC_MINTER: 'icCKBTCMinter',
  IC_CANISTERS_PPV: 'icPPV',
  IC_CANISTERS_TIPPING: 'icTipping',
  IC_CANISTERS_SUBSCRIPTIONS: 'icSubscriptions',
  IC_CANISTERS_CONTENT_MANAGER: 'icContentManager',
  IC_CANISTERS_CONTENT_ARTIST_ACCOUNT: 'icContentArtistAccount',
  IC_CANISTERS_CONTENT_ARTIST_CONTENT: 'icContentArtistContent',
  IC_CANISTERS_NFT: 'icNFT',
  IC_CANISTERS_IC_IDENTITY_PROVIDER: 'icIdentityProvider',
  IC_CANISTERS_TRAX_IDENTITY: 'icTraxIdentity',
  IC_CANISTERS_AIRDROP: 'icAirdrop',
  IC_CANISTERS_TRAX_TOKEN: 'icTraxToken',
  IC_CANISTERS_TRAX_ACCOUNT_PERCENTAGE: 'icTraxAccountPercentage',
  IC_CANISTERS_NFT_TICKET: 'icNFTTicket',
  IC_CANISTERS_NFT_SONG: 'icNFTSong',
  WALLET_CONNECT_PROJECT_ID: 'walletConnectProjectId'
};

export const GENRES = [
  { value: 'featured', text: 'Featured', short: true },
  { value: 'acoustic', text: 'Acoustic', short: true },
  { value: 'alternative', text: 'Alternative', short: true },
  { value: 'anime', text: 'Anime', short: true },
  { value: 'ambient', text: 'Ambient', short: true },
  { value: 'breakbeat', text: 'Breakbeat', short: true },
  { value: 'classical', text: 'Classical', short: true },
  { value: 'drum & bass', text: 'Drum and bass', short: true },
  { value: 'drill', text: 'Drill', short: true },
  { value: 'dance', text: 'Dance', short: true },
  { value: 'dub', text: 'Dub', short: true },
  { value: 'easy listening', text: 'Easy Listening', short: true },
  { value: 'electronic', text: 'Electronic', short: true },
  { value: 'electronica', text: 'Electronica', short: false },
  { value: 'funk', text: 'Funk', short: false },
  { value: 'garage', text: 'Garage', short: false },
  { value: 'grime', text: 'Grime', short: false },
  { value: 'hip-hop/rap', text: 'Hip-Hop/Rap', short: false },
  { value: 'holiday', text: 'Holiday', short: false },
  { value: 'house', text: 'House', short: false },
  { value: 'indie pop', text: 'Indie Pop', short: false },
  { value: 'jazz', text: 'Jazz', short: false },
  { value: 'jungle', text: 'Jungle', short: false },
  { value: 'k-pop', text: 'K-Pop', short: false },
  { value: 'latin', text: 'Latin', short: false },
  { value: 'lo-fi', text: 'Lo-fi', short: false },
  { value: 'metal', text: 'Metal', short: false },
  { value: 'opera', text: 'Opera', short: false },
  { value: 'pop', text: 'Pop', short: false },
  { value: 'reggae', text: 'Reggae', short: false },
  { value: 'rock', text: 'Rock', short: false },
  { value: 'r&b', text: 'R&B', short: false },
  { value: 'soundtrack', text: 'Soundtrack', short: false },
  { value: 'soul', text: 'Soul', short: false },
  { value: 'techno', text: 'Techno', short: false },
  { value: 'trance', text: 'Trance', short: false },
  { value: 'trap', text: 'Trap', short: false },
];

export const SHORT_GENRES = GENRES.filter((genre) => genre.short);

export const PICK_GENRES = GENRES.filter((genre) => genre.value !== 'featured');

export const MENU_SECTION = {
  MAIN: 'main',
  HEADER: 'header',
  FOOTER: 'footer'
};

export const RECEIVED_PAID_TOKEN_EVENT = 'RECEIVED_PAID_TOKEN_EVENT';
