export const SETTING_CHANNEL = 'SETTINGS';

export const SETTING_KEYS = {
  SITE_NAME: 'siteName',
  LOGO_URL: 'logoUrl',
  FAVICON: 'favicon',
  LOGIN_PLACEHOLDER_IMAGE: 'loginPlaceholderImage',
  REQUIRE_EMAIL_VERIFICATION: 'requireEmailVerification',
  ADMIN_EMAIL: 'adminEmail',
  SENDER_EMAIL: 'senderEmail',
  META_KEYWORDS: 'metaKeywords',
  META_DESCRIPTION: 'metaDescription',
  HEADER_SCRIPT: 'headerScript',
  AFTER_BODY_SCRIPT: 'afterBodyScript',
  MONTHLY_SUBSCRIPTION_COMMISSION: 'monthlySubscriptionCommission',
  YEARLY_SUBSCRIPTION_COMMISSION: 'yearlySubscriptionCommission',
  VIDEO_SALE_COMMISSION: 'videoSaleCommission',
  GALLERY_SALE_COMMISSION: 'gallerySaleCommission',
  PRODUCT_SALE_COMMISSION: 'productSaleCommission',
  FEED_SALE_COMMISSION: 'feedSaleCommission',
  TIP_COMMISSION: 'tipCommission',
  STREAM_COMMISSION: 'streamCommission',
  MESSAGE_COMMISSION: 'messageCommission',
  CCBILL_CLIENT_ACCOUNT_NUMBER: 'ccbillClientAccountNumber',
  CCBILL_DATALINK_USERNAME: 'ccbillDatalinkUsername',
  CCBILL_DATALINK_PASSWORD: 'ccbillDatalinkPassword',
  CCBILL_SUB_ACCOUNT_NUMBER: 'ccbillSubAccountNumber',
  CCBILL_FLEXFORM_ID: 'ccbillFlexformId',
  CCBILL_SALT: 'ccbillSalt',
  CCBILL_CURRENCY_CODE: 'ccbilCurrencyCode',
  USE_SENDGRID_TRANSPORTER: 'useSengridTransporter',
  SMTP_TRANSPORTER: 'smtpTransporter',
  GOOGLE_ANALYTICS_CODE: 'gaCode',
  MAINTENANCE_MODE: 'maintenanceMode',
  PERFORMER_VERIFY_NUMBER: 'performerVerifyNumber',
  TWITTER_CLIENT_ID: 'twitterClientId',
  TWITTER_CLIENT_SECRET: 'twitterClientSecret',
  GOOGLE_CLIENT_ID: 'googleClientId',
  GOOGLE_CLIENT_SECRET: 'googleClientSecret',
  VIEWER_URL: 'viewerURL',
  PUBLISHER_URL: 'publisherURL',
  SUBSCRIBER_URL: 'subscriberUrl',
  OPTION_FOR_BROADCAST: 'optionForBroadcast',
  OPTION_FOR_PRIVATE: 'optionForPrivate',
  OPTION_FOR_GROUP: 'optionForGroup',
  SECURE_OPTION: 'secureOption',
  ANT_MEDIA_API_ENDPOINT: 'AntMediaApiEndpoint',
  ANT_MEDIA_APPNAME: 'AntMediaAppname',
  ANT_MEDIA_ENTERPRISE: 'AntMediaEnterprise',
  FOOTER_CONTENT: 'footerContent',
  USER_BENEFIT: 'userBenefit',
  ARTIST_BENEFIT: 'artistBenefit',
  GOOGLE_RECAPTCHA_SITE_KEY: 'googleReCaptchaSiteKey',
  GOOGLE_RECAPTCHA_SECRET_KEY: 'googleReCaptchaSecretKey',
  ENABLE_GOOGLE_RECAPTCHA: 'enableGoogleReCaptcha',
  BITPAY_PRODUCTION_MODE: 'bitpayProductionMode',
  BITPAY_API_TOKEN: 'bitpayApiToken',
  TOKEN_CONVERSION_RATE: 'tokenConversionRate',
  STRIPE_PUBLISHABLE_KEY: 'stripePublishableKey',
  STRIPE_SECRET_KEY: 'stripeSecretKey',
  AGORA_APPID: 'agoraAppId',
  AGORA_ENABLE: 'agoraEnable',
  PAYMENT_GATEWAY: 'paymentGateway',
  IDENTITY_ONFIDO_API_TOKEN: 'identityOnfidoApiToken',
  IDENTITY_ONFIDO_SANDBOX: 'identityOnfidoSandbox',
  IDENTITY_ONFIDO_WORKFLOW_ID: 'identityOnfidoWorkflowId',
  IC_NETWORK: 'icNetwork',
  IC_ENABLE_IC_STORAGE: 'icEnableIcStorage',
  IC_HOST: 'icHost',
  IC_HOST_CONTENT_MANAGER: 'icHostContentManager',
  IC_CANISTERS_XRC: 'icXRC',
  IC_CANISTERS_LEDGER: 'icLedger',
  IC_CANISTERS_CKBTC_MINTER: 'icCKBTCMinter',
  IC_CANISTERS_PPV: 'icPPV',
  IC_CANISTERS_TIPPING: 'icTipping',
  IC_CANISTERS_SUBSCRIPTIONS: 'icSubscriptions',
  IC_CANISTERS_CONTENT_MANAGER: 'icContentManager',
  IC_CANISTERS_CONTENT_ARTIST_ACCOUNT: 'icContentArtistAccount',
  IC_CANISTERS_CONTENT_ARTIST_CONTENT: 'icContentArtistContent',
  IC_CANISTERS_NFT: 'icNFT',
  IC_CANISTERS_IC_IDENTITY_PROVIDER: 'icIdentityProvider',
  IC_CANISTERS_TRAX_IDENTITY: 'icTraxIdentity',
  IC_CANISTERS_AIRDROP: 'icAirdrop',
  IC_CANISTERS_TRAX_TOKEN: 'icTraxToken',
  IC_CANISTERS_TRAX_ACCOUNT_PERCENTAGE: 'icTraxAccountPercentage',
  IC_CANISTERS_NFT_TICKET: 'icNFTTicket',
  IC_CANISTERS_NFT_SONG: 'icNFTSong',
  WALLET_CONNECT_PROJECT_ID: 'walletConnectProjectId',
  STRIPE_FEES_PERCENTAGE_AMOUNT: 'stripeFeesPercentageAmount',
  STRIPE_FEES_FIXED_AMOUNT: 'stripeFeesFixedAmount',
  APPLE_CLIENT_ID: 'appleClientId',
  APPLE_CLIENT_SECRET: 'appleClientSecret',
  FACEBOOK_CLIENT_ID: 'facebooklientId',
  FACEBOOK_CLIENT_SECRET: 'facebookClientSecret'
};

export const GENRES = [
  { value: 'featured', text: 'featured', short: true },
  { value: 'acoustic', text: 'acoustic', short: true },
  { value: 'alternative', text: 'alternative', short: true },
  { value: 'anime', text: 'anime', short: true },
  { value: 'ambient', text: 'ambient', short: true },
  { value: 'breakbeat', text: 'breakbeat', short: true },
  { value: 'classical', text: 'classical', short: true },
  { value: 'drumbase', text: 'drum & bass', short: true },
  { value: 'drill', text: 'drill', short: true },
  { value: 'dance', text: 'dance', short: true },
  { value: 'dub', text: 'dub', short: true },
  { value: 'easylistening', text: 'easy listening', short: true },
  { value: 'electronic', text: 'electronic', short: true },
  { value: 'electronica', text: 'electronica', short: false },
  { value: 'funk', text: 'funk', short: false },
  { value: 'garage', text: 'garage', short: false },
  { value: 'grime', text: 'grime', short: false },
  { value: 'hiphop', text: 'hip-hop', short: false },
  { value: 'holiday', text: 'holiday', short: false },
  { value: 'house', text: 'house', short: false },
  { value: 'indiepop', text: 'indie pop', short: false },
  { value: 'jazz', text: 'jazz', short: false },
  { value: 'jungle', text: 'jungle', short: false },
  { value: 'kpop', text: 'k-pop', short: false },
  { value: 'latin', text: 'latin', short: false },
  { value: 'lofi', text: 'lo-fi', short: false },
  { value: 'metal', text: 'metal', short: false },
  { value: 'opera', text: 'opera', short: false },
  { value: 'pop', text: 'pop', short: false },
  { value: 'reggae', text: 'reggae', short: false },
  { value: 'rock', text: 'rock', short: false },
  { value: 'rb', text: 'r&b', short: false },
  { value: 'soundtrack', text: 'soundtrack', short: false },
  { value: 'soul', text: 'soul', short: false },
  { value: 'techno', text: 'techno', short: false },
  { value: 'trance', text: 'trance', short: false },
  { value: 'trap', text: 'trap', short: false },

  { value: 'homepage', text: 'homepage', short: false },
  { value: 'featuredVideoOne', text: 'featuredVideoOne', short: false },
  { value: 'traxOriginal', text: 'traxOriginal', short: false },
  { value: 'recommendedTrack', text: 'recommendedTrack', short: false },
  { value: 'popularTrack', text: 'popularTrack', short: false },
];

export const SHORT_GENRES = GENRES.filter((genre) => genre.short);

export const PICK_GENRES = GENRES.filter(
  (genre) =>
    ![
      'homepage',
      'featured',
      'featuredVideoOne',
      'traxOriginal',
      'recommendedTrack',
      'popularTrack',
    ].includes(genre.value)
);

export const MENU_SECTION = {
  MAIN: 'main',
  HEADER: 'header',
  FOOTER: 'footer'
};

export const RECEIVED_PAID_TOKEN_EVENT = 'RECEIVED_PAID_TOKEN_EVENT';
